use faers;

CREATE TABLE faers_demo (
    PRIMARYID VARCHAR(255) NOT NULL,
    CASEID VARCHAR(255) NOT NULL,
    CASEVERSION VARCHAR(255) NOT NULL,
    I_F_COD VARCHAR(255) NOT NULL,
    EVENT_DT VARCHAR(255),
    MFR_DT VARCHAR(255),
    INIT_FDA_DT VARCHAR(255),
    FDA_DT VARCHAR(255),
    REPT_COD VARCHAR(255),
    AUTH_NUM VARCHAR(255),
    MFR_NUM VARCHAR(255),
    MFR_SNDR VARCHAR(255),
    LIT_REF VARCHAR(255),
    AGE VARCHAR(255),
    AGE_COD VARCHAR(255),
    AGE_GRP VARCHAR(255),
    SEX VARCHAR(255),
    E_SUB VARCHAR(255),
    WT VARCHAR(255),
    WT_COD VARCHAR(255),
    REPT_DT VARCHAR(255),
    TO_MFR VARCHAR(255),
    OCCP_COD VARCHAR(255),
    REPORTER_COUNTRY VARCHAR(255),
    OCCR_COUNTRY VARCHAR(255),
    PRIMARY KEY (PRIMARYID, CASEID, CASEVERSION)
);

DROP TABLE faers_drug;
CREATE TABLE faers_drug (
    PRIMARYID VARCHAR(255) NOT NULL,
    CASEID VARCHAR(255) NOT NULL,
    DRUG_SEQ VARCHAR(255) NOT NULL,
    ROLE_COD VARCHAR(255),
    DRUGNAME TEXT NOT NULL,
    PROD_AI TEXT,
    VAL_VBM VARCHAR(255),
    ROUTE VARCHAR(255),
    DOSE_VBM TEXT,
    CUM_DOSE_CHR TEXT,
    CUM_DOSE_UNIT VARCHAR(255),
    DECHAL VARCHAR(255),
    RECHAL VARCHAR(255),
    LOT_NUM TEXT,
    EXP_DT VARCHAR(255),
    NDA_NUM VARCHAR(255),
    DOSE_AMT TEXT,
    DOSE_UNIT VARCHAR(255),
    DOSE_FORM TEXT,
    DOSE_FREQ VARCHAR(255),
    PRIMARY KEY (PRIMARYID, CASEID, DRUG_SEQ)
);

DROP TABLE faers_reac;
CREATE TABLE faers_reac (
    PRIMARYID VARCHAR(255) NOT NULL,
    CASEID VARCHAR(255) NOT NULL,
    PT TEXT NOT NULL,
    DRUG_REC_ACT TEXT
);

DROP TABLE faers_outc;
CREATE TABLE faers_outc (
    PRIMARYID VARCHAR(255) NOT NULL,
    CASEID VARCHAR(255) NOT NULL,
    OUTC_COD VARCHAR(255) NOT NULL
);

DROP TABLE faers_ther;
CREATE TABLE faers_ther (
    PRIMARYID VARCHAR(32) NOT NULL,
    CASEID VARCHAR(32) NOT NULL,
    DSG_DRUG_SEQ VARCHAR(4) NOT NULL,
    START_DT VARCHAR(16),
    END_DT VARCHAR(16),
    DUR VARCHAR(16),
    DUR_COD VARCHAR(16)
);

DROP TABLE  faers_indi;
CREATE TABLE faers_indi (
    PRIMARYID VARCHAR(255) NOT NULL,
    CASEID VARCHAR(255) NOT NULL,
    INDI_DRUG_SEQ VARCHAR(255) NOT NULL,
    INDI_PT TEXT,
    PRIMARY KEY (PRIMARYID)
);

DROP TABLE faers_rpsr;
CREATE TABLE faers_rpsr (
    PRIMARYID VARCHAR(255) NOT NULL,
    CASEID VARCHAR(255) NOT NULL,
    RPSR_COD VARCHAR(255) NOT NULL,
    PRIMARY KEY (PRIMARYID)
);